// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssiqlzagctlgrkdqeugk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzaXFsemFnY3RsZ3JrZHFldWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDUwNDIsImV4cCI6MjA3MDA4MTA0Mn0.ZxcviHSx1fB6uFfay9PU6m4tmqwPynPNCPGAc1pggIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});